import React, { useCallback, useState } from 'react';
import Header from './Header';
import { useDropzone } from 'react-dropzone'
import { FileArchive, FileCheck, FileUp, Trash2, Trophy, Upload } from "lucide-react";
import { SummaryObj } from '../model/SummaryObj';

function UploadPage() {

    const [files, setFiles] = useState<File[]>([]);
    const [summary, setSummary] = useState<SummaryObj | null>(null);
    const [text, setText] = useState<Boolean>(false);

    const onDrop = useCallback((acceptedFiles: File[]) => {
        const reader = new FileReader()

        reader.onabort = () => console.log('file reading was aborted')
        reader.onerror = () => console.log('file reading has failed')
        reader.onload = () => {

            const json = JSON.parse(reader.result as string)
            console.log(json);
            setSummary(new SummaryObj(json));


        }
        console.log(acceptedFiles[0]);
        reader.readAsText(acceptedFiles[0])


        return setFiles(acceptedFiles);
    }, [])

    const { getRootProps, getInputProps, isDragActive } = useDropzone({ onDrop })


    // useEffect(() => {
    //     console.log(files);
    // }, [files])

    // TODO: Implement uploader -> send to parent component to set state variables
    return (
        <div className="flex flex-col h-screen">
            <Header />
            <div className='flex items-center h-full'>
                <div className="flex w-screen justify-center">
                    <div className='space-y-4'>
                        <div className='max-w-[35rem] bg-white p-4 rounded-lg border'>
                            <div className='text-text-color font-semibold flex text-xl'>
                                <h1>Watch and Analyze Poker Bot Matches</h1>
                            </div>
                            <div className='flex text-left text-xs'>
                                <p className='text-text-color'>
                                    Upload a summary.json file from a match between two poker bots to watch and analyze their gameplay. This file can be generated by running the poker bot engine and retrieving it from the logs directory.  {text && "The summary.json contains comprehensive details about the match, such as the bots' actions and overall statistics. Each match up consists of several hundred poker rounds due to the tournament format, where two bots play a unique 1v1 variation of Texas Hold'em. You can also explore and review matches played by your peers' poker bots if they share their game summary files with you."} <span className='font-bold cursor-pointer' onClick={(() => setText(!text))}>{text ? "(Less)" : "(Show more)"}</span>
                                </p>
                            </div>
                        </div>
                        <div className='bg-white px-4 py-4 rounded-lg border shadow-sm space-y-5 max-w-[35rem]  '>
                            {/* Header */}
                            <div>
                                <div className='flex justify-between flex-1 items-center'>
                                    <div className='flex space-x-2 items-center'>
                                        <div>
                                            <FileUp className='text-text-color size-6 cursor-pointer hover:scale-105 transition-all' />
                                        </div>
                                        <div>
                                            <h1 className='text-text-color text-xl font-semibold'>
                                                Upload your Game Summary File
                                            </h1>
                                        </div>
                                    </div>
                                </div>
                                <div className='text-text-color flex justify-start text-sm  ml-1'>
                                    <p>Upload your Summary <span className='font-medium'>.json</span> file</p>
                                </div>
                            </div>
                            {/* Dropzone */}
                            <div>
                                <div {...getRootProps()} className='bg-green-500/10 hover:bg-green-500/5 transition-all cursor-pointer'>
                                    <input type='file'  {...getInputProps()} />
                                    <div className='border border-dashed rounded-md  hover:border-solid transition-all  flex justify-center px-9 py-14 border-green-700'>


                                        {
                                            isDragActive
                                                ?
                                                <div>
                                                    <div className='flex flex-col justify-center'>
                                                        <div className='flex justify-center'>
                                                            <FileCheck className='text-green-600 size-6' />
                                                        </div>
                                                        <div className='text-text-color font-medium text-sm'>
                                                            <p>Drop your files here</p>
                                                        </div>
                                                    </div>
                                                </div>
                                                :
                                                <div>
                                                    <div className='flex flex-col justify-center'>
                                                        <div className='flex justify-center'>
                                                            <FileArchive className='text-green-600 size-6' />
                                                        </div>
                                                        <div className='text-text-color font-medium text-sm'>
                                                            <p>Drag & drop your files here</p>
                                                        </div>
                                                    </div>
                                                </div>
                                        }
                                    </div>
                                </div>
                                {/* Footer */}
                                <div className='text-text-color flex text-xs font-medium mt-2'>
                                    <p>Only <span className='font-bold'>.json</span> are allowed</p>
                                </div>

                                {/* Filedisplay */}
                                {files.length > 0 && (
                                    <>
                                        <div className='flex mt-4 text-sm font-medium'>
                                            <span className='text-text-color'>File</span>
                                        </div>
                                        <div className='mt-1'>
                                            {files.map((file, index) => (
                                                <>
                                                    <div key={index} className='  border rounded-md py-3 px-3'>
                                                        <div className='flex justify-between items-center '>
                                                            <div className='flex space-x-3 items-center'>
                                                                <div className='border p-2 rounded-full hover:bg-slate-100 transition-all'>
                                                                    <Upload className='text-text-color size-4' />
                                                                </div>
                                                                <div className='flex flex-col'>
                                                                    <div className='text-text-color font-semibold'>
                                                                        <p className='text-sm'>{file.name}</p>
                                                                    </div>
                                                                    <div className='text-text-color flex text-xs font-medium'>
                                                                        <p className=''>{file.size / 1000} KB</p>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div className='p-2 hover:ring-1 rounded-full hover:ring-slate-400 transition-all cursor-pointer ' onClick={(() => setFiles([]))}>
                                                                <Trash2 className='text-text-color size-4' />
                                                            </div>
                                                        </div>

                                                        <div className='h-[2.8px] rounded-full w-full bg-slate-300 mt-2' />

                                                    </div>

                                                    {/* Summary-Infos */}
                                                    <div className=''>
                                                        <div className='flex mt-4 text-sm font-medium'>
                                                            <span className='text-text-color'>Infos</span>
                                                        </div>
                                                        <div className='mt-1 border rounded-md py-3 px-3'>
                                                            <div className='flex space-x-3 items-center'>
                                                                <div className='border p-2 rounded-full hover:bg-slate-100 transition-all'>
                                                                    <Trophy className='text-text-color size-4' />
                                                                </div>
                                                                <div className='flex flex-col'>
                                                                    <div className='text-text-color flex font-semibold'>
                                                                        <p className='text-sm'>Match:</p>
                                                                    </div>
                                                                    <div className='text-text-color flex text-xs font-medium'>
                                                                        <p className=''>{summary?.playerStats[0].name} <span className='font-bold'>vs</span> {summary?.playerStats[1].name}</p>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>

                                                    <div className='flex justify-end mt-5'>
                                                        <button className='border-text-color hover:border-text-color/40 transition-all border text-text-color w-[8rem] h-9 font-medium rounded-md'>Start game</button>
                                                    </div>


                                                </>
                                            ))}
                                        </div>
                                    </>
                                )}
                            </div>



                        </div>
                    </div>

                </div>
            </div>

        </div>
    );
}

export default UploadPage;